version: "3.9"

services:
  # Контейнер с Python и JupyterLab серваком
  jupyter-lab:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./:/home/jovyan/work
    networks:
      - docker_network

  influxdb:
    image: influxdb:2.7.10
    container_name: influxdb_btc
    restart: unless-stopped
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=12345678
      - DOCKER_INFLUXDB_INIT_ORG=admin
      - DOCKER_INFLUXDB_INIT_BUCKET=admin
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=admin
    ports:
      # HTTP API
      - "8010:8086"  
      # InfluxDB UI
      - "8011:8088"  
    volumes:
      - influxdb_data:/var/lib/influxdb
    networks:
      - docker_network

volumes:
  influxdb_data:
    driver: local

networks:
  docker_network:
    driver: bridge
  
